title: Relación de las cosas sucedidas en el Río de la Plata
email: hdlabconicet@gmail.com
description: 
baseurl: "/Relacion-de-las-cosas-sucedidas" 
url: "https://hdlab.space"
github_repo: Relacion-de-las-cosas-sucedidas
twitter_username: hdlabconicet
github_username:  hdlabconicet
facebook_username: HDLAB.CONICET

social_link: twitter
social_username: hdlabconicet

theme_color: light

# Build settings
markdown: kramdown

collections:
    pero_pages:
      output: true
    recursos:
      output: true
    nombres_destacados:
      output: true
