title: Relación de las cosas sucedidas en el Río de la Plata
email: hdcaicyt@gmail.com
description: 
baseurl: "/Relacion-de-las-cosas-sucedidas" 
url: "https://hdlab.space"
github_repo: Relacion-del-descubrimiento
twitter_username: HDCAICYT
github_username:  hdcaicyt
facebook_username: HDCAICYTLAB

social_link: twitter
social_username: hdcaicyt

theme_color: light

# Build settings
markdown: kramdown

collections:
    pero_pages:
      output: true
    recursos:
      output: true
    nombres_destacados:
      output: true
